const LOGIN = "LOGIN"
const LOGOUT = "LOGOUT"
const GET_UPLOADED_DATA = "GET_UPLOADED_DATA"
const REQUESTSENT = "REQUESTSENT"
const DOWNLOAD_INC = "DOWNLOAD_INC"
const GET_CONTRIBUTOR = "GET_CONTRIBUTOR"

export { LOGIN, LOGOUT, GET_UPLOADED_DATA, REQUESTSENT, DOWNLOAD_INC, GET_CONTRIBUTOR }