const LOGIN = "LOGIN"
const LOGOUT ="LOGOUT"
const GET_UPLOADED_DATA ="GET_UPLOADED_DATA"
const REQUESTSENT = "REQUESTSENT"
const DATA_UPLOADED ="DATA_UPLOADED"
export {LOGIN,LOGOUT,GET_UPLOADED_DATA,REQUESTSENT ,DATA_UPLOADED}